version: "3.8"

services:
  nest_server:
    build:
      context: ./api_gate_way
      dockerfile: Dockerfile
    image: nest_server
    env_file:
      - ./.env
    ports:
      - 80:3000
    container_name: api_gate_way
    command: npm run start:prod
