version: "3.8"

services:
  nest_server:
    build:
      context: ./api_gate_way
      dockerfile: Dockerfile
    image: nest_server
    env_file:
      - ./.env
    ports:
      - 80:3000
    container_name: api_gate_way
    command: npm run start:prod
    depends_on:
      - fastapi_server

  fastapi_server:
    build:
      context: ./ai/ji
      dockerfile: Dockerfile
    image: python_server
    env_file:
      - ./.env
    expose:
      - 80:80
    container_name: fastapi_server
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
